// 로그인
export const FETCH_SIGN_IN = 'FETCH_SIGN_IN';
export const FETCH_SIGN_IN_FULFILLED = 'FETCH_SIGN_IN_FULFILLED';
export const FETCH_SIGN_IN_REJECTED = 'FETCH_SIGN_IN_REJECTED';

// 로그아웃
export const SIGN_OUT = 'SIGN_OUT';

// 회원가입
export const FETCH_SIGN_UP = 'FETCH_SIGN_UP';
export const FETCH_SIGN_UP_FULFILLED = 'FETCH_SIGN_UP_FULFILLED';
export const FETCH_SIGN_UP_REJECTED = 'FETCH_SIGN_UP_REJECTED';

// 회원가입 인증메일 재전송
export const FETCH_RE_SEND_VERIFY_EMAIL = 'FETCH_RE_SEND_VERIFY_EMAIL';
export const FETCH_RE_SEND_VERIFY_EMAIL_FULFILLED = 'FETCH_RE_SEND_VERIFY_EMAIL_FULFILLED';
export const FETCH_RE_SEND_VERIFY_EMAIL_REJECTED = 'FETCH_RE_SEND_VERIFY_EMAIL_REJECTED';

// 현재 유저정보 가져오기
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_FULFILLED = 'FETCH_CURRENT_USER_FULFILLED';
export const FETCH_CURRENT_USER_REJECTED = 'FETCH_CURRENT_USER_REJECTED';
